### ISSUE TITLE
this.applicationContext.getLatestValue(...).getValue is not a function

### ISSUE THREAD

**Issue by RalekArts** [stayintarkov/SIT.Docker#1]
After building and running the docker image, I run into this error:

```
[2024-01-06T02:14:46.956Z] debug: 	Importing configs...
[2024-01-06T02:14:47.012Z] info: 	Commit hash: db70e8e4bc480f551b7c71b886e4a72c0e99b469
[2024-01-06T02:14:47.013Z] info: 	Build date: 1704507207647
[2024-01-06T02:14:47.054Z] info: 	ModLoader: loading 1 server mods...
[2024-01-06T02:14:47.055Z] info: 	ModLoader: order.json is missing, creating...
[2024-01-06T02:14:47.062Z] warn: 	Mod Paulov-sit-coop is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
[2024-01-06T02:14:47.067Z] debug: 	Mod SITCoop hash stored in ./user/cache/modCache.json
[2024-01-06T02:14:47.982Z] info: 	Mod: sit-coop version: 1.5.1 by: Paulov loaded
[2024-01-06T02:14:48.538Z] info: 	Server: executing startup callbacks...
[2024-01-06T02:14:48.539Z] debug: 	OS: x64 | #9-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct  7 01:35:40 UTC 2023 | linux
[2024-01-06T02:14:48.539Z] debug: 	CPU: DO-Premium-Intel cores: 1
[2024-01-06T02:14:48.540Z] debug: 	RAM: 1.91GB
[2024-01-06T02:14:48.540Z] debug: 	PATH: L29wdC9zZXJ2ZXIvQWtpLlNlcnZlci5leGU=
[2024-01-06T02:14:48.541Z] debug: 	PATH: L29wdC9zZXJ2ZXIvQWtpLlNlcnZlci5leGU=
[2024-01-06T02:14:48.541Z] debug: 	Server: 3.7.6
[2024-01-06T02:14:48.541Z] debug: 	Date: 1704507207647
[2024-01-06T02:14:48.541Z] debug: 	Commit: db70e8e4bc480f551b7c71b886e4a72c0e99b469
[2024-01-06T02:14:48.542Z] info: 	Importing database...
[2024-01-06T02:19:10.591Z] debug: 	Importing configs...
[2024-01-06T02:19:10.656Z] info: 	Commit hash: db70e8e4bc480f551b7c71b886e4a72c0e99b469
[2024-01-06T02:19:10.657Z] info: 	Build date: 1704507207647
[2024-01-06T02:19:10.693Z] info: 	ModLoader: loading 1 server mods...
[2024-01-06T02:19:10.696Z] warn: 	Mod Paulov-sit-coop is not compatible with the current version of AKI. You may encounter issues - no support will be provided!
[2024-01-06T02:19:10.714Z] info: 	Mod: sit-coop version: 1.5.1 by: Paulov loaded
[2024-01-06T02:19:11.211Z] info: 	Server: executing startup callbacks...
[2024-01-06T02:19:11.212Z] debug: 	OS: x64 | #9-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct  7 01:35:40 UTC 2023 | linux
[2024-01-06T02:19:11.212Z] debug: 	CPU: DO-Premium-Intel cores: 1
[2024-01-06T02:19:11.213Z] debug: 	RAM: 1.91GB
[2024-01-06T02:19:11.213Z] debug: 	PATH: L29wdC9zZXJ2ZXIvQWtpLlNlcnZlci5leGU=
[2024-01-06T02:19:11.213Z] debug: 	PATH: L29wdC9zZXJ2ZXIvQWtpLlNlcnZlci5leGU=
[2024-01-06T02:19:11.214Z] debug: 	Server: 3.7.6
[2024-01-06T02:19:11.214Z] debug: 	Date: 1704507207647
[2024-01-06T02:19:11.214Z] debug: 	Commit: db70e8e4bc480f551b7c71b886e4a72c0e99b469
[2024-01-06T02:19:11.216Z] info: 	Importing database...
[2024-01-06T02:19:26.077Z] info: 	Database import finished
[2024-01-06T02:19:30.667Z] succ: 	Started webserver at http://0.0.0.0:6969
[2024-01-06T02:19:30.668Z] succ: 	Started websocket at ws://0.0.0.0:6969
[2024-01-06T02:19:30.669Z] succ: 	Server is running, do not close while playing SPT, Happy playing!!
[2024-01-06T02:19:50.004Z] info: 	[Client Request] /launcher/profile/login
[2024-01-06T02:19:54.858Z] info: 	[Client Request] /launcher/profile/register
[2024-01-06T02:19:54.876Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 10.576652999967337ms to save.
[2024-01-06T02:19:55.224Z] info: 	[Client Request] /launcher/profile/login
[2024-01-06T02:19:55.685Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 7.305564999580383ms to save.
[2024-01-06T02:20:00.090Z] info: 	[Client Request] /singleplayer/bundles
[2024-01-06T02:20:00.416Z] info: 	[Client Request] /launcher/profile/login
[2024-01-06T02:20:04.640Z] info: 	[Client Request] /launcher/profile/login
[2024-01-06T02:20:04.727Z] info: 	[Client Request] /launcher/profile/register
[2024-01-06T02:20:04.741Z] debug: 	Profile 41ee27f8217c8efdcaca7e3d took 11.792015999555588ms to save.
[2024-01-06T02:20:04.815Z] info: 	[Client Request] /launcher/profile/login
[2024-01-06T02:20:09.850Z] info: 	[Client Request] /singleplayer/bundles
[2024-01-06T02:20:10.083Z] info: 	[Client Request] /launcher/profile/register
[2024-01-06T02:20:10.097Z] debug: 	Profile 17283d560a3a0580543f1a51 took 11.935844998806715ms to save.
[2024-01-06T02:20:10.275Z] info: 	[Client Request] /launcher/profile/login
[2024-01-06T02:20:11.348Z] info: 	[Client Request] /client/game/start
[2024-01-06T02:20:11.350Z] debug: 	Added custom boss wave to factory4_day of type sptBear, time: -1, chance: 25, zone: BotZone
[2024-01-06T02:20:11.350Z] debug: 	Added custom boss wave to factory4_day of type sptUsec, time: -1, chance: 25, zone: BotZone
[2024-01-06T02:20:11.350Z] debug: 	Added custom boss wave to bigmap of type sptBear, time: -1, chance: 25, zone: ZoneScavBase
[2024-01-06T02:20:11.350Z] debug: 	Added custom boss wave to bigmap of type sptUsec, time: -1, chance: 25, zone: ZoneScavBase
[2024-01-06T02:20:11.350Z] debug: 	Added custom boss wave to woods of type sptBear, time: -1, chance: 25, zone: ZoneScavBase2
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to woods of type sptUsec, time: -1, chance: 25, zone: ZoneScavBase2
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to shoreline of type sptBear, time: -1, chance: 20, zone: ZonePort
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to shoreline of type sptUsec, time: -1, chance: 20, zone: ZonePort
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to shoreline of type sptUsec, time: -1, chance: 10, zone: ZoneSanatorium1
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to shoreline of type sptBear, time: -1, chance: 10, zone: ZoneSanatorium1
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to shoreline of type sptUsec, time: -1, chance: 10, zone: ZoneSanatorium2
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to shoreline of type sptBear, time: -1, chance: 10, zone: ZoneSanatorium2
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to laboratory of type sptBear, time: -1, chance: 15, zone: BotZoneFloor1
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to laboratory of type sptBear, time: -1, chance: 15, zone: BotZoneFloor2
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to laboratory of type sptBear, time: -1, chance: 15, zone: BotZoneBasement
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to laboratory of type sptUsec, time: -1, chance: 15, zone: BotZoneFloor1
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to laboratory of type sptUsec, time: -1, chance: 15, zone: BotZoneFloor2
[2024-01-06T02:20:11.351Z] debug: 	Added custom boss wave to laboratory of type sptUsec, time: -1, chance: 15, zone: BotZoneBasement
[2024-01-06T02:20:11.352Z] debug: 	Added custom boss wave to interchange of type sptBear, time: -1, chance: 15, zone: ZoneCenter,ZoneCenterBot,ZoneOLI,ZoneIDEA,ZoneGoshan,ZonePowerStation
[2024-01-06T02:20:11.352Z] debug: 	Added custom boss wave to interchange of type sptUsec, time: -1, chance: 15, zone: ZoneCenter,ZoneCenterBot,ZoneOLI,ZoneIDEA,ZoneGoshan,ZonePowerStation
[2024-01-06T02:20:11.352Z] debug: 	Added custom boss wave to lighthouse of type sptBear, time: -1, chance: 15, zone: Zone_Village,Zone_Chalet,Zone_DestroyedHouse,Zone_Rocks,Zone_OldHouse
[2024-01-06T02:20:11.352Z] debug: 	Added custom boss wave to lighthouse of type sptUsec, time: -1, chance: 15, zone: Zone_Village,Zone_Chalet,Zone_DestroyedHouse,Zone_Rocks,Zone_OldHouse
[2024-01-06T02:20:11.352Z] debug: 	Added custom boss wave to rezervbase of type sptBear, time: -1, chance: 15, zone: ZoneBarrack,ZonePTOR1,ZonePTOR2,ZoneSubCommand,ZoneSubStorage,ZoneRailStrorage
[2024-01-06T02:20:11.352Z] debug: 	Added custom boss wave to rezervbase of type sptUsec, time: -1, chance: 15, zone: ZoneBarrack,ZonePTOR1,ZonePTOR2,ZoneSubCommand,ZoneSubStorage,ZoneRailStrorage
[2024-01-06T02:20:11.587Z] info: 	[Client Request] /client/menu/locale/en
[2024-01-06T02:20:11.818Z] info: 	[Client Request] /client/game/version/validate
[2024-01-06T02:20:12.038Z] info: 	[Client Request] /client/languages
[2024-01-06T02:20:12.275Z] info: 	[Client Request] /client/game/config
[2024-01-06T02:20:13.790Z] info: 	[Client Request] /client/items
[2024-01-06T02:20:14.020Z] info: 	[Client Request] /singleplayer/bundles
[2024-01-06T02:20:15.695Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 0.14000499993562698ms to save.
[2024-01-06T02:20:15.709Z] debug: 	Profile 41ee27f8217c8efdcaca7e3d took 11.52165300026536ms to save.
[2024-01-06T02:20:15.714Z] debug: 	Profile 17283d560a3a0580543f1a51 took 4.21051099896431ms to save.
[2024-01-06T02:20:20.050Z] info: 	[Client Request] /client/game/start
[2024-01-06T02:20:20.138Z] info: 	[Client Request] /client/menu/locale/en
[2024-01-06T02:20:20.239Z] info: 	[Client Request] /client/game/version/validate
[2024-01-06T02:20:20.309Z] info: 	[Client Request] /client/languages
[2024-01-06T02:20:20.400Z] info: 	[Client Request] /client/game/config
[2024-01-06T02:20:20.643Z] info: 	[Client Request] /client/customization
[2024-01-06T02:20:20.878Z] info: 	[Client Request] /client/game/start
[2024-01-06T02:20:20.971Z] info: 	[Client Request] /client/globals
[2024-01-06T02:20:21.030Z] info: 	[Client Request] /client/menu/locale/en
[2024-01-06T02:20:21.182Z] info: 	[Client Request] /client/game/version/validate
[2024-01-06T02:20:21.340Z] info: 	[Client Request] /client/languages
[2024-01-06T02:20:21.475Z] info: 	[Client Request] /client/game/config
[2024-01-06T02:20:21.691Z] info: 	[Client Request] /client/items
[2024-01-06T02:20:22.294Z] info: 	[Client Request] /client/trading/api/traderSettings
[2024-01-06T02:20:22.382Z] info: 	[Client Request] /client/items
[2024-01-06T02:20:22.971Z] info: 	[Client Request] /client/settings
[2024-01-06T02:20:23.204Z] info: 	[Client Request] /client/game/profile/list
[2024-01-06T02:20:23.440Z] info: 	[Client Request] /client/locale/en
[2024-01-06T02:20:23.620Z] info: 	[Client Request] /client/account/customization
[2024-01-06T02:20:24.746Z] info: 	[Client Request] /client/locale/ru
[2024-01-06T02:20:25.440Z] info: 	[Client Request] /client/locale/ge
[2024-01-06T02:20:25.830Z] info: 	[Client Request] /client/game/profile/nickname/reserved
[2024-01-06T02:20:27.177Z] info: 	[Client Request] /client/customization
[2024-01-06T02:20:27.409Z] info: 	[Client Request] /client/globals
[2024-01-06T02:20:27.922Z] info: 	[Client Request] /client/trading/api/traderSettings
[2024-01-06T02:20:28.057Z] info: 	[Client Request] /client/settings
[2024-01-06T02:20:28.190Z] info: 	[Client Request] /client/game/profile/list
[2024-01-06T02:20:28.341Z] info: 	[Client Request] /client/locale/en
[2024-01-06T02:20:28.439Z] info: 	[Client Request] /client/account/customization
[2024-01-06T02:20:29.025Z] info: 	[Client Request] /client/locale/ru
[2024-01-06T02:20:29.758Z] info: 	[Client Request] /client/locale/ge
[2024-01-06T02:20:30.272Z] info: 	[Client Request] /client/locale/fr
[2024-01-06T02:20:30.377Z] info: 	[Client Request] /client/customization
[2024-01-06T02:20:30.544Z] info: 	[Client Request] /client/game/profile/nickname/validate
[2024-01-06T02:20:30.599Z] info: 	[Client Request] /client/globals
[2024-01-06T02:20:31.301Z] info: 	[Client Request] /client/trading/api/traderSettings
[2024-01-06T02:20:31.385Z] info: 	[Client Request] /client/settings
[2024-01-06T02:20:31.451Z] info: 	[Client Request] /client/game/profile/nickname/reserved
[2024-01-06T02:20:31.475Z] info: 	[Client Request] /client/game/profile/list
[2024-01-06T02:20:31.575Z] info: 	[Client Request] /client/locale/en
[2024-01-06T02:20:31.641Z] info: 	[Client Request] /client/account/customization
[2024-01-06T02:20:32.151Z] info: 	[Client Request] /client/locale/ru
[2024-01-06T02:20:32.735Z] info: 	[Client Request] /client/locale/ge
[2024-01-06T02:20:32.919Z] info: 	[Client Request] /client/game/profile/nickname/reserved
[2024-01-06T02:20:35.696Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 0.18999100103974342ms to save.
[2024-01-06T02:20:35.696Z] debug: 	Profile 41ee27f8217c8efdcaca7e3d took 0.06582299992442131ms to save.
[2024-01-06T02:20:35.696Z] debug: 	Profile 17283d560a3a0580543f1a51 took 0.03365600109100342ms to save.
[2024-01-06T02:20:37.010Z] info: 	[Client Request] /client/game/profile/nickname/validate
[2024-01-06T02:20:37.735Z] info: 	[Client Request] /client/game/profile/create
[2024-01-06T02:20:37.766Z] debug: 	unable to sort 17 slots, no slots found
[2024-01-06T02:20:37.767Z] debug: 	unable to sort 4 slots, no slots found
[2024-01-06T02:20:37.767Z] debug: 	unable to sort 20 slots, no slots found
[2024-01-06T02:20:37.767Z] debug: 	unable to sort 6 slots, no slots found
[2024-01-06T02:20:37.767Z] debug: 	Updating generator area slots to a size of 6 + hideout management skill
[2024-01-06T02:20:37.767Z] debug: 	Updating water collector area slots to a size of 1 + hideout management skill
[2024-01-06T02:20:37.767Z] debug: 	Updating air filter area slots to a size of 3 + hideout management skill
[2024-01-06T02:20:37.768Z] debug: 	Updating bitcoin farm area slots to a size of 50 + hideout management skill
[2024-01-06T02:20:37.812Z] debug: 	generated player scav loadout with karma level 0
[2024-01-06T02:20:37.855Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 9.3496039994061ms to save.
[2024-01-06T02:20:37.857Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 2.0324440002441406ms to load.
[2024-01-06T02:20:37.866Z] debug: 	Profile 414441a231b77b2b76c9e2e1 took 7.604437999427319ms to save.
[2024-01-06T02:20:38.090Z] info: 	[Client Request] /client/game/profile/list
[2024-01-06T02:20:38.316Z] info: 	[Client Request] /client/game/profile/nickname/validate
[2024-01-06T02:20:38.590Z] info: 	[Client Request] /client/game/profile/select
[2024-01-06T02:20:38.799Z] info: 	[Client Request] /client/profile/status
[2024-01-06T02:20:39.019Z] info: 	[Client Request] /client/weather
[2024-01-06T02:20:39.077Z] error: 	TypeError: this.applicationContext.getLatestValue(...).getValue is not a function
[2024-01-06T02:20:39.090Z] error: 	TypeError: this.applicationContext.getLatestValue(...).getValue is not a function
[2024-01-06T02:20:39.093Z] error: 	TypeError: this.applicationContext.getLatestValue(...).getValue is not a function
    at WeatherGenerator.getInRaidTime (/snapshot/project/src/generators/WeatherGenerator.ts:71:14)
    at WeatherGenerator.getBsgFormattedInRaidTime (/snapshot/project/src/generators/WeatherGenerator.ts:57:44)
    at WeatherGenerator.calculateGameTime (/snapshot/project/src/generators/WeatherGenerator.ts:43:26)
    at WeatherController.generate (/snapshot/project/src/controllers/WeatherController.ts:29:40)
    at WeatherCallbacks.getWeather (/snapshot/project/src/callbacks/WeatherCallbacks.ts:24:65)
    at RouteAction.action (/snapshot/project/src/routers/static/WeatherStaticRouter.ts:14:46)
    at WeatherStaticRouter.handleStatic (/snapshot/project/src/di/Router.ts:50:63)
    at HttpRouter.handleRoute (/snapshot/project/src/routers/HttpRouter.ts:79:62)
    at HttpRouter.getResponse (/snapshot/project/src/routers/HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (/snapshot/project/src/servers/http/AkiHttpListener.ts:150:38)
[2024-01-06T02:20:39.086Z] error: 	TypeError: this.applicationContext.getLatestValue(...).getValue is not a function
    at WeatherGenerator.getInRaidTime (/snapshot/project/src/generators/WeatherGenerator.ts:71:14)
    at WeatherGenerator.getBsgFormattedInRaidTime (/snapshot/project/src/generators/WeatherGenerator.ts:57:44)
    at WeatherGenerator.calculateGameTime (/snapshot/project/src/generators/WeatherGenerator.ts:43:26)
    at WeatherController.generate (/snapshot/project/src/controllers/WeatherController.ts:29:40)
    at WeatherCallbacks.getWeather (/snapshot/project/src/callbacks/WeatherCallbacks.ts:24:65)
    at RouteAction.action (/snapshot/project/src/routers/static/WeatherStaticRouter.ts:14:46)
    at WeatherStaticRouter.handleStatic (/snapshot/project/src/di/Router.ts:50:63)
    at HttpRouter.handleRoute (/snapshot/project/src/routers/HttpRouter.ts:79:62)
    at HttpRouter.getResponse (/snapshot/project/src/routers/HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (/snapshot/project/src/servers/http/AkiHttpListener.ts:150:38)
```

This is likely an AKI-specific error, but it does not occur in the official release.

**Comment by devbence** [comment]
@RalekArts please checkout the latest master, i tested it on an amazon lightsail instance:
![image](https://github.com/stayintarkov/SIT.Docker/assets/936368/5aac35de-766f-4da6-9f5e-eaeb8189ab65)
